/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sisvendas.view.user.menu;

import java.awt.AWTEvent;
import java.awt.EventQueue;
import java.awt.Toolkit;
import java.awt.event.AWTEventListener;
import java.awt.event.KeyEvent;
import java.beans.Beans;
import java.io.IOException;
import java.text.NumberFormat;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import javax.persistence.NoResultException;
import javax.persistence.Query;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import sisvendas.bean.admin.Produto;
import sisvendas.bean.admin.Usuario;
import sisvendas.bean.admin.Venda;

/**
 *
 * @author Neto
 */
public class ViewCaixa extends javax.swing.JFrame {

    /**
     * Creates new form ViewCaixa
     */
    
   NumberFormat moeda = NumberFormat.getCurrencyInstance(); 
   NumberFormat porcentagem = NumberFormat.getPercentInstance();
   private Double vlrTotalItem;
 
   private Venda vendas;
   private List<Venda> listaDVendas = new LinkedList<>();
   private  DefaultListModel lm = new DefaultListModel<>();
   private int item;
   private boolean isItemCancelado;
   private Double valorCancelado;
   private Usuario u = new Usuario();
  
    
    public ViewCaixa() {
        Toolkit.getDefaultToolkit().addAWTEventListener( new AWTEventListener()
		{
			public void eventDispatched(AWTEvent e)
			{
			}
		}, AWTEvent.KEY_EVENT_MASK);
        initComponents();
        setIcone();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("bc_teste?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("select p from Produto p");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        codigoField = new javax.swing.JTextField();
        descricaoField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        quantidadeField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        vlrUnitarioField = new javax.swing.JTextField();
        lblLegenda = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        lblTotalGeral = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dinheiroField = new javax.swing.JTextField();
        chequeField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        descontoField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        totalDinheiroField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        subTotalField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        valorRecebidoField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        trocoField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SISVENDAS");
        setBackground(new java.awt.Color(0, 0, 204));

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Código:");

        codigoField.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        codigoField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        codigoField.setFocusable(false);
        codigoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoFieldActionPerformed(evt);
            }
        });

        descricaoField.setEditable(false);
        descricaoField.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        descricaoField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        descricaoField.setEnabled(false);
        descricaoField.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quantidade:");

        quantidadeField.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        quantidadeField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        quantidadeField.setFocusable(false);
        quantidadeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantidadeFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Valor Unitário:");

        vlrUnitarioField.setEditable(false);
        vlrUnitarioField.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        vlrUnitarioField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        vlrUnitarioField.setEnabled(false);
        vlrUnitarioField.setFocusable(false);

        lblLegenda.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblLegenda.setForeground(new java.awt.Color(255, 255, 255));
        lblLegenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codigoField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descricaoField, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantidadeField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vlrUnitarioField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLegenda, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codigoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descricaoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLegenda, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(vlrUnitarioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(quantidadeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 70));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(4);
        jTextArea1.setText("<F1>Ajuda | <F2> Calculadora | <F3> Abre Venda | <F4> Abre Caixa | <F5> Desconto | <F6> Cancela Item | \n<F7> Pesquisa Item p/  incluir na venda | <F8> Cancela Venda | <F9> Fecha Venda | <F10> Pesquisa Item | <F11> Reservas\n\n                                                               NSN Sistemas - e-mail: niltoncons@gmail.com");
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setBorder(null);
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
        );

        jList1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jList1.setModel(lm);
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setFocusable(false);
        jScrollPane2.setViewportView(jList1);

        jPanel3.setBackground(new java.awt.Color(0, 0, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total da compra:");

        lblTotalGeral.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblTotalGeral.setForeground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(0, 0, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Pagamento");

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("1 - Dinheiro:");

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("2 - Cheque:");

        dinheiroField.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        dinheiroField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        dinheiroField.setFocusable(false);
        dinheiroField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dinheiroFieldKeyPressed(evt);
            }
        });

        chequeField.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        chequeField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        chequeField.setFocusable(false);
        chequeField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                chequeFieldKeyPressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Desconto:");

        descontoField.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        descontoField.setEnabled(false);
        descontoField.setFocusable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel9)
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(descontoField))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chequeField))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dinheiroField)))
                .addGap(24, 24, 24))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(dinheiroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(chequeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(descontoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Total em dinheiro:");

        totalDinheiroField.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        totalDinheiroField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        totalDinheiroField.setFocusable(false);

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("SubTotal:");

        subTotalField.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        subTotalField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        subTotalField.setFocusable(false);

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Valor Recebido:");

        valorRecebidoField.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        valorRecebidoField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        valorRecebidoField.setFocusable(false);

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Troco:");

        trocoField.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        trocoField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        trocoField.setEnabled(false);
        trocoField.setFocusable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(subTotalField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(65, Short.MAX_VALUE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valorRecebidoField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trocoField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalDinheiroField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalDinheiroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subTotalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valorRecebidoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trocoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblTotalGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(830, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dinheiroFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dinheiroFieldKeyPressed
       
        int x = evt.getKeyCode();
        if (x == KeyEvent.VK_ENTER){
            chequeField.setFocusable(true);
            chequeField.requestFocus();
        }
          
       
    }//GEN-LAST:event_dinheiroFieldKeyPressed

    private void chequeFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chequeFieldKeyPressed
        Double din,chq,totalDin,troco;
        int x = evt.getKeyCode();
        if (x == KeyEvent.VK_ENTER){
                if (dinheiroField.getText().isEmpty()){//caso receba em cheque
                     din = 0.0;
                     chq = Double.parseDouble(chequeField.getText());                
                     totalDin = retornaTotalEmDinheiro(din, chq);
                     totalDinheiroField.setText(moeda.format(totalDin));
                     subTotalField.setText(moeda.format(getVlrTotalItem()));
                     valorRecebidoField.setText(moeda.format(totalDin));
                     trocoField.setEnabled(false);
                      chequeField.setFocusable(false);
                     
                }else if(chequeField.getText().isEmpty()){// recebe em dinheiro
                    chq = 0.0;
                    din = Double.parseDouble(dinheiroField.getText());                      
                    totalDin = retornaTotalEmDinheiro(din, chq);
                    totalDinheiroField.setText(moeda.format(totalDin));
                  //  subTotalField.setText(moeda.format(1000.00));
                    valorRecebidoField.setText(moeda.format(totalDin));
                    troco = retornaTroco(this.getVlrTotalItem(), totalDin);
                    if (troco != 0.0){//Devolve troco se tiver
                        trocoField.setText(moeda.format(troco));
                        trocoField.setEnabled(true);
                        chequeField.setFocusable(false);
                    }
                    chequeField.setFocusable(false);
                 
                }else{//Caso receba os dois
                    din = Double.parseDouble(dinheiroField.getText());  
                    chq = Double.parseDouble(chequeField.getText());                
                    totalDin = retornaTotalEmDinheiro(din, chq);
                    totalDinheiroField.setText(moeda.format(totalDin));
                    troco = retornaTroco(this.getVlrTotalItem(), totalDin);
                 if (troco != 0.0){//Devolve troco se tiver
                        trocoField.setText(moeda.format(troco));
                        trocoField.setEnabled(true);
                    }
                 chequeField.setFocusable(false);
                }                  
               
        }
      
    }//GEN-LAST:event_chequeFieldKeyPressed
/**/
    private void codigoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoFieldActionPerformed
       Long l = Long.valueOf(codigoField.getText()); 
      preparaVenda();
      descricaoField.setText(retornaProduto(l).get(0).getDescricao());
        
    }//GEN-LAST:event_codigoFieldActionPerformed

    private void quantidadeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantidadeFieldActionPerformed
         int x = 0;
        Double aux = 0.0;
        Double conta;
        Double prd;
        Produto prod = new Produto();
        Long l = Long.valueOf(codigoField.getText());
        Long pr = retornaProduto(l).get(0).getCodigo();
        prd = retornaProduto(l).get(0).getPreco();
        prod.setCodigo(pr); 
     
        this.u.setCodigo(Integer.parseInt(jLabel4.getText()));       
       vendas = new Venda();        
       conta = Double.parseDouble(quantidadeField.getText())*prd;
      quantidadeField.setFocusable(false);
      vendas.setCodProduto(prod);
      vendas.setCodUsuario(u);
      vendas.setQtde(Integer.parseInt(quantidadeField.getText()));
      vendas.setTotal(conta);
      vendas.setItem(this.getItem());
      this.listaDVendas.add(vendas);
      lm.addElement("Cod."+"                       "+"Descr.");
      lm.addElement(prod.getCodigo()+" "+descricaoField.getText());
      lm.addElement("Item"+"Vlr. unit."+"         "+"Qtde."+"    "+"Vlr. total");
      lm.addElement(vendas.getItem()+1+"    "+vlrUnitarioField.getText()+"                           "+quantidadeField.getText()+"            "+
              moeda.format(conta));
 
         Iterator<Venda> it = listaDVendas.iterator(); 
            while (it.hasNext()) {
           Venda v = it.next();
           aux = aux + v.getTotal();
            x++;
           
       }
       this.setItem(x);        
       this.setVlrTotalItem(aux);
       subTotalField.setText(moeda.format(aux));
       lblTotalGeral.setText(moeda.format(aux));
     limpaCabecalho();
    }//GEN-LAST:event_quantidadeFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(final String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        final ViewCaixa vc = new ViewCaixa();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
           
            public void run() {
               vc.setVisible(true);
               vc.jLabel4.setText(args[0]);
               vc.jLabel4.setVisible(false);
            }
           });
       
         
	EventQueue queue = new EventQueue()
		{ 
                    protected void dispatchEvent(AWTEvent event)
			{
                            super.dispatchEvent(event);
				
					String a[];
					String tecla[];
					
					if (!event.paramString().equals("")) {
						if  (event.paramString().substring(0, 5).equals("KEY_P")) {
							a = event.paramString().split(",");
							tecla = a[1].split("=");

							switch (Integer.parseInt(tecla[1])) {
							case 112: //F1
								JOptionPane.showMessageDialog(null, "Pressionou F1!");
								break;
							case 113: //F2
								try {
										Runtime.getRuntime().exec("calc.exe");
									} catch (IOException e) {
										e.printStackTrace();
									}
								break;
							case 114: //F3
								vc.abreVenda();
								break;
							case 115: //F4
								vc.abreCaixa();
								break;
							case 116: //F5
								String desc = JOptionPane.showInputDialog("Insira o valor do desconto: (Ex.:10% digite apenas 10)");
                                                                vc.trataDesconto(desc);
								break;
							case 117: //F6
								String item = JOptionPane.showInputDialog("Qual item deseja cancelar? ");
								vc.cancelaItem(Integer.parseInt(item));
								break;
							case 118: //F7
								String p = JOptionPane.showInputDialog("Qual item deseja pesquisar? ");
                                                                vc.retornaPesquisa(p);
								break;
							case 119: //F8
								vc.cancelaVenda();
								break;
							case 120: //F9
								vc.finalizaVenda();
								break;
							case 121: //F10
								vc.chamaOpcao(2);
								break;
							case 122: //F11
								vc.chamaOpcao(1);
								break;
							case 123: //F12
								vc.chamaOpcao(3);
								break;
							default:
								break;
							}
						}
					}
			}
                    
		};
		Toolkit.getDefaultToolkit().getSystemEventQueue().push(queue);	
	
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField chequeField;
    private javax.swing.JTextField codigoField;
    private javax.swing.JTextField descontoField;
    private javax.swing.JTextField descricaoField;
    private javax.swing.JTextField dinheiroField;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblLegenda;
    private javax.swing.JLabel lblTotalGeral;
    private java.util.List list;
    private javax.swing.JTextField quantidadeField;
    private javax.persistence.Query query;
    private javax.swing.JTextField subTotalField;
    private javax.swing.JTextField totalDinheiroField;
    private javax.swing.JTextField trocoField;
    private javax.swing.JTextField valorRecebidoField;
    private javax.swing.JTextField vlrUnitarioField;
    // End of variables declaration//GEN-END:variables

//--------------Inicio bloco funções de controle de componentes--------------------    
private void focusController(boolean y){
    if (y == true){
    boolean x = true;
    codigoField.setFocusable(x);
    quantidadeField.setFocusable(x);
    codigoField.requestFocus(x);
    }else{
    boolean x = false;
    codigoField.setFocusable(true);
    codigoField.requestFocus();
    quantidadeField.setFocusable(x);
    dinheiroField.setFocusable(x);
    chequeField.setFocusable(x);
  //  descontoField.setFocusable(x);
    }
}
private void limpaCabecalho(){
   codigoField.setText("");
   descricaoField.setText("");
   quantidadeField.setText("");
   vlrUnitarioField.setText("");
   codigoField.requestFocus(true);
}

private void limpaCorpo(){
    dinheiroField.setText("");
    chequeField.setText("");
    totalDinheiroField.setText("");
    descontoField.setText("");
    descontoField.setEnabled(false);
    subTotalField.setText("");
    valorRecebidoField.setText("");
    trocoField.setText("");
    trocoField.setEnabled(false);
    lblTotalGeral.setText("");
    lblLegenda.setText("");
    lm.clear();
    
    // falta codigo da venda e total geral 
}
private void abreVenda(){
    if (!entityManager.getTransaction().isActive())
        entityManager.getTransaction().begin();
    if (!this.listaDVendas.isEmpty())
    this.listaDVendas.clear();
    else
     focusController(true);
    lblLegenda.setText("Venda Aberta");
}
private void finalizaVenda(){
       
    for (Venda venda : listaDVendas) {
            entityManager.persist(venda);
               }
      entityManager.getTransaction().commit();   
    limpaCorpo();
   
    JOptionPane.showMessageDialog(null, "Venda encerrada");
    
}
private void abreCaixa(){
    dinheiroField.setFocusable(true);
    dinheiroField.requestFocus(true);
    lblLegenda.setText("Caixa Aberto");
   
}
private void cancelaVenda(){
    limpaCabecalho();
    limpaCorpo();
    JOptionPane.showMessageDialog(null, "Venda Cancelada!","Cancela", JOptionPane.INFORMATION_MESSAGE);
}
private void preparaVenda(){
        try{              
     
        quantidadeField.setFocusable(true);
        quantidadeField.requestFocus(true);
        quantidadeField.setText(Integer.toString(1));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "O campo código não pode estar vazio.\nFavor digitar o código do produto.", "Erro",JOptionPane.ERROR_MESSAGE);
        }

}
private void cancelaItem(int x){
    int y = x-1;
    int aux = 0;
    Double ajusta;
    Iterator<Venda> it = listaDVendas.iterator(); 
            while (it.hasNext()) {
           Venda v = it.next();
           if (v.getItem() == y){
              lm.addElement("ITEM: "+v.getItem()+"     CANCELADO!");
              aux = y;             
           }
        }
       Venda getVenda = listaDVendas.get(aux);
        this.setValorCancelado(getVenda.getTotal());
          ajusta = this.getVlrTotalItem()-this.getValorCancelado();
          this.setVlrTotalItem(ajusta);
          subTotalField.setText(moeda.format(ajusta));
          lblTotalGeral.setText(moeda.format(ajusta));
          listaDVendas.remove(aux);
          
              
}
/* Calcula o valor com desconto */
private void trataDesconto(String x){
    
    Double sub;
          
    descontoField.setText(porcentagem.format((Double.parseDouble(x))/100));
    descontoField.setEnabled(true);
    sub = retornaSubTotal(this.getVlrTotalItem(), Double.parseDouble(x));
    subTotalField.setText(moeda.format(sub));
    lblTotalGeral.setText(subTotalField.getText());
    this.setVlrTotalItem(sub);
}
private void chamaOpcao(int x){
    String args[] = new String[1];
    switch(x){
        case 1:
             args[0] = "SISVENDAS - Reserva de Itens";
             ReservaSimples.main(args); 
            break;
        case 2:
             args[0] = "SISVENDAS - Pesquisa de Itens";
            ConsultaProduto.main(args);
            break;
         case 3:
             args[0] = jLabel4.getText();
            MovimentoCaixa.main(args);
            dispose();
            break;   
    }
   
}

 /* Retorna o item selecionado pelo codigo de barras */   


private List<Produto> retornaProduto (Long cod){
 
    Query q = entityManager.createNamedQuery("Produto.findByCodigo");
    q.setParameter("codigo", cod);
    List <Produto> p = q.getResultList();
     return p;  
}


private void retornaPesquisa(String nome){
    try{
    Query q = entityManager.createNamedQuery("Produto.findByDescricao");
    q.setParameter("descricao", nome);
    Produto codigo = (Produto) q.getSingleResult();
    preparaVenda();
    codigoField.setText(String.valueOf(codigo.getCodigo()));
    }catch (NoResultException nr){
        JOptionPane.showMessageDialog(null, "Produto não encontrado", "SISVENDAS - Erro", JOptionPane.ERROR_MESSAGE);
    }
 }
    public Double getVlrTotalItem() {
        return vlrTotalItem;
    }

    public void setVlrTotalItem(Double vlrTotalItem) {
        this.vlrTotalItem = vlrTotalItem;
    }

    public int getItem() {
        return item;
    }

    public void setItem(int item) {
        this.item = item;
    }

    public boolean isIsItemCancelado() {
        return isItemCancelado;
    }

    public void setIsItemCancelado(boolean isItemCancelado) {
        this.isItemCancelado = isItemCancelado;
    }

    public Double getValorCancelado() {
        return valorCancelado;
    }

    public void setValorCancelado(Double valorCancelado) {
        this.valorCancelado = valorCancelado;
    }

  


//--------------Fim do bloco funções de controle de componentes--------------------

//--------------Inicio bloco funções financeiras--------------------

/* Funcao que retorna a soma dos pagamentos efetuados*/
public Double retornaTotalEmDinheiro(Double dinheiro,Double cheque){
     return dinheiro+cheque;
}
/* Funcao que retorna o subtotal */
public Double retornaSubTotal(Double totalGeral,Double desconto){
     return totalGeral - (totalGeral*(desconto/100));
}
/* Funcao que retorna o troco se o valor recebido for maior que o subtotal */
public Double retornaTroco(Double subTotal,Double vlrRec){
    Double x;
    if (subTotal < vlrRec){
        x = vlrRec - subTotal;
    }else{
        x = 0.0;
    }
    return x;
}

//--------------Fim do bloco funções financeiras--------------------

    private void setIcone() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("finance.png")));
    }



}
// implementar registro de mensalidade e doaçao no F7